---
# Default configuration

configure_dotfiles: no
configure_sudoers: no
configure_terminal: no
configure_osx: no

dotfiles_repo: <set-me>
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/src/dotfiles
dotfiles_files:
  - .aliases
  - .bash_profile
  - .bashrc
  - .config/git/ignore
  - .gitconfig
  - .git-prompt
  # - .osx
  - .screenrc
  - .ssh/config.d/common
  - .vimrc
  - bin/2mp3
  - bin/exif-keywords
  - bin/flushdns
  - bin/foreach
  - bin/rvm-activate
  - bin/sbash
  - bin/screen-ssh-agent
  - bin/spine
  - bin/tcmount

homebrew_installed_packages:
  # - ansible # Installed via homebrew
  - autoconf
  - autossh
  - bash-completion
  - coreutils
  - duplicity
  - exiftool
  - fping
  - gettext
  - gifsicle
  - git
  - github/gh/gh
  - gpg
  - libevent
  - mpc
  - nmap
  - readline
  - openssl
  - qemu
  - rsync
  - sqlite
  - tcpdump
  - tree
  - tmux
  - watch
  - wget

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - clementine
  # - darktable
  # - firefox
  - flux
  # - gimp
  # - github
  # - google-chrome
  # - handbrake
  # - inkscape
  - iterm2
  # - keepassx
  # - keepassxc
  # - moneydance
  # - nextcloud
  # - slack
  - sublime-text
  # - tunnelblick
  # - vagrant
  # - vagrant-manager
  # - virtualbox
  # - virtualbox-extension-pack
  - vlc

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Ruby
ruby_versions:
  - "2.7.1"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
  # - bundler
  # - rake
  # - rubocop
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []


# Configure iTerm2
iterm2_defaults:
  # General -> Closing
  - name: PromptOnQuit
    type: bool
    value: false
  # Appearance -> Windows
  - name: UseBorder
    type: bool
    value: true
  # Appearance -> Tabs
  - name: HideTab
    type: bool
    value: false
  # Pointer -> General
  - name: ThreeFingerEmulates
    type: bool
    value: true
  - name: FocusFollowsMouse
    type: bool
    value: true
