---
# Default configuration

downloads: ~/.ansible-downloads/

configure_dock: true
configure_sudoers: false
configure_dotfiles: true
configure_terminal: false
configure_osx: false
configure_sublime: false
configure_iterm: true
configure_ruby: true
configure_homebrew: true

dockitems_remove:
  - Calendar
  - Contacts
  - FaceTime
  - iBooks
  - Launchpad
  - Mail
  - Maps
  - Messages
  - Music
  - News
  - Notes
  - Photos
  - Podcasts
  - Reminders
  - Siri
  - TV

dockitems_persist:
  # - name: Finder
  #   path: ""
  #   pos: 1
  - name: iTerm
    path: "/Applications/iTerm.app"
    pos: 2
  - name: Firefox
    path: "/Applications/Firefox.app"
    pos: 3
  - name: Safari
    path: "/Applications/Safari.app"
    pos: 4
  - name: Thunderbird
    path: "/Applications/Thunderbird.app"
    pos: 5
  - name: Slack
    path: "/Applications/Slack.app"
    pos: 6
  - name: Sublime Text
    path: "/Applications/Sublime Text.app"
    pos: 7
  - name: strawberry
    path: "/Applications/strawberry.app"
    pos: 8
  - name: KeePassXC
    path: "/Applications/KeePassXC.app"
    pos: 11
  - name: System Preferences
    path: "/Applications/System Preferences.app"
    pos: 12

sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: git.xr7.org:/srv/repo/home.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/src/dotfiles
dotfiles_files:
  - .aliases
  - .bash_profile
  - .bashrc
  - .config/gh/config.yml
  - .config/gh/hosts.yml
  - .config/git/ignore
  - .gitconfig
  - .gitignore
  - .git-prompt
  - .screenrc
  - .ssh/config.d/common
  # - .ssh/config.d/xr7
  - .vimrc
  - bin/2mp3
  - bin/ddnsupdate
  - bin/exif-keywords
  - bin/flushdns
  - bin/foreach
  - bin/rvm-activate
  - bin/sbash
  - bin/screen-ssh-agent
  - bin/spine
  - bin/split-repo.sh
  - bin/tcmount
  - lib/Makefile

homebrew_installed_packages:
  - autoconf
  - autossh
  - bash-completion
  - cdrtools
  - coreutils
  - dockutil
  - duplicity
  - exiftool
  - fping
  - gettext
  - gh
  - gifsicle
  - git
  - gpg
  - libevent
  - mosh
  - mpc
  - nmap
  - openssl
  - python@3.9
  - qemu
  - readline
  - rsync
  - sqlite
  - tcpdump
  - tmux
  - tree
  - watch
  - wget

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  # - barrier
  # - darktable
  - dockutil
  - firefox
  - flux
  - gimp
  # - github
  # - google-chrome
  # - handbrake
  # - inkscape
  - iterm2
  - keepassxc
  # - moneydance
  - nextcloud
  - slack
  - strawberry
  - sublime-text
  - thunderbird
  - tunnelblick
  # - vagrant
  # - vagrant-manager
  # - virtualbox
  # - virtualbox-extension-pack
  - vlc

homebrew_taps:
  - homebrew/core
  - homebrew/cask

dockutil_install: false

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

Configure_Assistant: yes
Assistant_Enabled: no

Configure_DateTime: yes                          # Enable Date Time configuration
DateTime_TimeZone: "America/Chicago"             # Set the timezone; see `systemsetup -listtimezones` for other values
DateTime_AutomaticTimeZone: no                   # Set time zome automatically using current location
DateTime_DateFormat: "EEE MMM d HH:mm:ss"        # Menu bar clock format ("h:mm": Default, "HH": Use a 24-hour clock, "a": Show AM/PM, "ss": Display the time with seconds

Configure_Dashboard: yes                         # Enable Dashboard configuration
Dashboard_McxDisabled: no                        # Disable Dashboard
Dashboard_EnabledState: 3                        # Dashboard state (1: Off, 2: As Space, 3: As Overlay)
# Dashboard_DontShowAsSpace: yes                   # Don’t show Dashboard as a Space
# Dashboard_DevMode: no                            # Enable Dashboard dev mode (allows keeping widgets on the desktop)

Configure_Dock: yes                              # Enable Dock configuration
Dock_PersistentApps: []                          # A plain path string, if empty [] it won't change anything
  # - /Applications/Safari.app
  # - /Applications/System Preferences.app
Dock_PersistentOthers:                           # Either a plain path string or a dict like "{path: /path, type: [file | directory], arrange: [1-5] }"
  - /Applications
  # - { path: "~/Downloads", type: directory, arrange: 2}
  # - { path: "/Applications/Firefox.app", type: file, arrange: 3}
Dock_TileSize: 32                                # Dock size
Dock_Magnification: no                           # Dock magnification
Dock_LargeSize: 128                              # Icon size of magnified Dock items
Dock_Orientation: "left"                         # Dock orientation: left, bottom, right

Dock_SpacesMRU: no                               # Rearrange spaces

Configure_Finder: yes                            # Enable Finder configuration
Finder_ShowHardDrivesOnDesktop: yes              # Show hard drives on the desktop
# Finder_ShowExternalHardDrivesOnDesktop: yes      # Show external hard drives on the desktop
# Finder_ShowRemovableMediaOnDesktop: yes          # Show CDs,DVDs and iPods on the desktop
Finder_ShowMountedServersOnDesktop: yes          # Show connected servers on the desktop
Finder_NewWindowTarget: "Home"                   # New Finder windows shows ("Computer", "Computer's HD", "Home", "Desktop", "Documents", "All My Files" )
Finder_FinderSpawnTab: no                        # Open folders in tabs instead of new windows
Finder_AppleShowAllExtensions: yes               # Show all fiename extensions
Finder_FXEnableExtensionChangeWarning: no        # Show warning before changing an extension
Finder_WarnOnEmptyTrash: no                      # Show warning before emptying the trash
Finder_FXDefaultSearchScope: "SCsp"              # When performing a search (SCev:Search This Mac, SCcf:Search the Current Folder, SCsp:Use the Previous Search Scope)
# Finder_AppleShowAllFiles: no                     # Show hidden files
Finder_FXPreferredViewStyle: "clmv"              # View as (icnv:Icons, Nlsv:List, clmv:Column, Flwv:Cover Flow)
# Finder_FXPreferredGroupBy: "None"                # Arrange By (None, Name, Application Category, Date Last Opened, Date Added, Size, Finder Tags)
Finder_ShowTabView: no                           # Show Tab Bar
# Finder_ShowPathbar: no                           # Show Path Bar
Finder_ShowStatusBar: yes                        # Show Status Bar
# Finder_ShowSidebar: yes                          # Show Side Bar
Finder_ColumnShowIcons: no                       # Show Preview
Finder_FXShowPosixPathInTitle: yes               # Show full POSIX path as Finder window title
# Finder_QuitMenuItem: no                          # Allow quitting via ⌘ + Q
Finder_QLEnableTextSelection: yes                # Select and Copy Text from Quick Look

Finder_ShowRecentTags: no                        # Show Recent Tags
Finder_SidebarShowingSignedIntoiCloud: no        # Show iCloud

Configure_General: yes                           # Enable General configuration
General_AppleInterfaceStyle: "Dark"              # Use Dark menu bar and Dock (Empty or "Dark")
General_AppleHighlightColor: "Blue"              # Highlight color (Red, Orange, Yellow, Green, Blue, Purple, Pink, Brown, Graphite)
General_SidebarIconSize: 1                       # Sidebar icon size (Small: 1, Medium: 2, Large: 3)
General_AppleShowScrollBars: "Always"            # Scroll bar visibility (WhenScrolling, Automatic, Always)
General_CloseWindowsWhenQuittingApp: yes         # Close windows when quitting an application

General_AppleAccentColor: 5                      # Purple
General_MouseTrackingSpeed: 2

Configure_HotCorners: yes                        # Enable Hot Corners configura  tions
                                                 # HotCorners Available Actions:
                                                 #     - { name: "no-op", value: 0 }
                                                 #     - { name: "Disabled", value: 1 }
                                                 #     - { name: "Mission Control", value: 2 }
                                                 #     - { name: "Show Application Windows", value: 3 }
                                                 #     - { name: "Desktop", value: 4 }
                                                 #     - { name: "Start Screen Saver", value: 5 }
                                                 #     - { name: "Disable Screen Saver", value: 6 }
                                                 #     - { name: "Dashboard", value: 7 }
                                                 #     - { name: "Put Display To Sleep", value: 10 }
                                                 #     - { name: "Launchpad", value: 11 }
                                                 #     - { name: "Notification Center", value: 12 }
HotCorners_BottomLeftModifier: "Enabled"         # Enabled, Disabled
HotCorners_BottomRightModifier: "Enabled"        # Enabled, Disabled
HotCorners_TopLeftModifier: "Enabled"            # Enabled, Disabled
HotCorners_TopRightModifier: "Enabled"           # Enabled, Disabled

HotCorners_BottomLeftAction: "Start Screen Saver"
HotCorners_BottomRightAction: "Desktop"
HotCorners_TopLeftAction: "Disable Screen Saver"
HotCorners_TopRightAction: "Mission Control"

Configure_ICloud: no                             # Enable iCloud configuration
ICloud_NSDocumentSaveNewDocumentsToCloud: no     # Save to iCloud by default

Configure_Keyboard: yes                          # Enable Keyboard configuration
Keyboard_KeyRepeat: 6                            # Set key repeat rate (Off: 300000, Slow: 120, Fast: 2)
Keyboard_InitialKeyRepeat: 20                    # Set delay until repeat, in milliseconds (Long: 120, Short: 15)
# Keyboard_fnState: no                             # Use F1, F2, etc. keys as standard function keys
# Keyboard_kDim: no                                # Adjust keyboard brightness in low light
# Keyboard_kDimTime: 0                             # Dim keyboard after idle time (in seconds, 0 is Never)
# Keyboard_AutomaticSpellingCorrectionEnabled: no  # Correct spelling automatically
# Keyboard_AutomaticQuoteSubstitutionEnabled: no   # Use smart quotes
# Keyboard_AutomaticDashSubstitutionEnabled: no    # Use smart dashes
# Keyboard_AutomaticPeriodSubstitutionEnabled: no  # Automatic period substitution
# Keyboard_AppleKeyboardUIMode: "All controls"     # Full Keyboard Access (1 : Text boxes and lists only, 3 : All controls)
# Keyboard_PowerButtonSleepsSystem: no             # Prevent accidental Power button presses from sleeping system
# Keyboard_PressAndHoldEnabled: no                 # Disable press-and-hold for keys in favor of key repeat

Configure_LoginWindow: yes                       # Enable Launch Services configuration
LoginWindow_LoginWindowText: "{{ ansible_hostname }}" # Text message to show in the login screen
LoginWindow_DesktopPicture: ""                   # Change login screen background

Configure_Trackpad: yes                          # Enable Trackpad configuration
Trackpad_Clicking: yes                           # Tap to Click
#Trackpad_ForceClickAndHapticFeedback: no          # Force Click and haptic feedback
Trackpad_ScrollDirectionNatural: no                # Enable Natural Scroll Direction (it's a macOS default)

iterm2_defaults:
  # General -> Closing
  - name: PromptOnQuit
    type: bool
    value: false
  # Appearance -> Windows
  - name: UseBorder
    type: bool
    value: true
  # Appearance -> Tabs
  - name: HideTab
    type: bool
    value: false
  # Pointer -> General
  - name: ThreeFingerEmulates
    type: bool
    value: true
  - name: FocusFollowsMouse
    type: bool
    value: true
  - name: LoadPrefsFromCustomFolder
    type: bool
    value: false
  - name: PrefsCustomFolder
    type: string
    value: "/Users/dtroyer/Cloud/etc/iTerm"

rvm1_gpg_key_server: hkp://keys.gnupg.net
ruby_versions:
  - "2.5.1"
  - "2.6.3"
  - "2.7.1"
  - "2.7.2"
  - "2.7.4"
  # - "3.0.0"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
