---
- name: Configure host.
  hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

    - name: Ensure ~/bin directory exists
      file:
        path: ~/bin
        state: directory

    - name: Ensure .~/ssh/config.d directory exists
      file:
        path: ~/.ssh/config.d
        state: directory

  roles:
    - role: lafarer.osx-defaults
      tags: ['defaults']
    - role: geerlingguy.mac.homebrew
      when: configure_homebrew
      tags: ['homebrew']
    - role: tkimball83.iterm2
      tags: ['iterm']
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']
    - role: geerlingguy.mac.mas
      when: mas_installed_apps or mas_installed_app_ids
      tags: ['mas']
    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ['dock']
    - role: rvm.ruby
      rvm1_rubies: "{{ ruby_versions }}"
      rvm1_install_flags: '--autolibs=enable --user-install'
      rvm1_user: "{{ ansible_env.USER }}"
      when: configure_ruby
      tags: ['ruby']

  tasks:
    - import_tasks: tasks/extra-defaults.yml
      tags: ['defaults']

    - import_tasks: tasks/sudoers.yml
      when: configure_sudoers
      tags: ['sudoers']

    - import_tasks: tasks/terminal.yml
      when: configure_terminal
      tags: ['terminal']

    - import_tasks: tasks/osx.yml
      when: configure_osx
      tags: ['osx']

    - import_tasks: tasks/extra-packages.yml
      tags: ['extra-packages']

    - import_tasks: tasks/sublime-text.yml
      when: configure_sublime
      tags: ['sublime-text']

    # - import_tasks: tasks/ruby.yml
    #   when: configure_ruby
    #   tags: ['ruby']

    - name: Run post-provision task files in a block.
      tags: ['post']
      block:
        - name: Run configured post-provision ansible task files.
          include_tasks: "{{ outer_item }}"
          loop_control:
            loop_var: outer_item
          with_fileglob: "{{ post_provision_tasks | default(omit) }}"
