---
- block:

  - name: "Assistant"
    osx_defaults: { domain: 'com.apple.assistant.support', key: "{{ item.key }}", type: "{{ item.type }}", value: "{{ item.value }}" }
    loop:
      - { key: 'Assistant Enabled', type: 'bool', value: '{{ Assistant_Enabled }}'}
    when: item.value | string | length > 0
    notify: Restart Dock
  # Privilege escalation to `target_user_id` is only required for inner steps when
  # the `target_user_id` doesn't match the `ansible_user_id`
  become: "{{ target_user_id != ansible_user_id }}"
  become_user: "{{ target_user_id }}"
