---
- block:

  - name: "Dock - Mission Control"
    osx_defaults: { domain: 'com.apple.dock', key: "{{ item.key }}", type: "{{ item.type }}", value: "{{ item.value }}" }
    loop:
      - { key: 'mru-spaces',               type: 'bool',   value: '{{ Dock_SpacesMRU }}'}
      # set `version` and `mod-count` to '1' to prevent DockFixUp to be replace the whole Dock in case of a new user
    when: item.value | string | length > 0
    notify: Restart Dock
  # Privilege escalation to `target_user_id` is only required for inner steps when
  # the `target_user_id` doesn't match the `ansible_user_id`
  become: "{{ target_user_id != ansible_user_id }}"
  become_user: "{{ target_user_id }}"
